# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-bubba"
BBFILE_PATTERN_meta-bubba = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-bubba = "6"

LAYERDEPENDS_meta-bubba = "core"
LAYERSERIES_COMPAT_meta-bubba = "scarthgap"
IMAGE_BOOT_FILES:append = " i2c1.dtbo;overlays/i2c1.dtbo"
